### ISSUE TITLE
Kernel reset

### ISSUE THREAD

**Issue by ManRod2982** [UDOOboard/uboot-imx#7]
Hi all, 

I am facing an issue with this U-boot version, the Linux kernel seems to be loaded just fine but at the middle of loading all the modules the board resets and U-boot starts again. I suspect of the watchdog but I am not really sure (I'm a beginner).

To compile I do the following:
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make udoo_qd_defconfig
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make

When I compile I get the following warnings:
board/udoo/udoo_qd/udoo.c:180:13: warning: ‘setup_iomux_wdog’ defined but not used [-Wunused-function]
 static void setup_iomux_wdog(void)

board/udoo/udoo_qd/udoo.c:180:13: warning: ‘setup_iomux_wdog’ defined but not used [-Wunused-function]
 static void setup_iomux_wdog(void)

Using the image that is on the web it boots without issue and I think the only difference is that this version of U-boot is 2015.04 and the one in the image is U-boot 2015.10.

Thanks!

**Comment by cyrilfr** [comment]
Hi,

This is because, for no documented reason, the [2015.04.imx](https://github.com/UDOOboard/uboot-imx/tree/2015.04.imx) branch still have a UDOO Quad/Dual config file but doesn't support it anymore! 

To compile for a UDOO Quad/Dual, you must switch to [2015.10.fslc-qdl](https://github.com/UDOOboard/uboot-imx/tree/2015.10.fslc-qdl) branch ;)

If the repository maintainers can fix this issue, it will be a great step forward for OpenEmbedded support of UDOO boards :)

**Comment by ManRod2982** [comment]
Thank you very much Cyrilfr, that did the trick!!
